import pandas as pd
from pathlib import Path

# ---------------------------------------------------------
# Traffic Classification
# ---------------------------------------------------------

# Input CSV generated by vehicle_counting.py
input_file = Path("outputs/traffic_counts.csv")

# Output CSV
output_file = Path("outputs/traffic_classification.csv")

# Read vehicle count data
df = pd.read_csv(input_file)


# ---------------------------------------------------------
# Classify traffic based on vehicle count
# ---------------------------------------------------------

def classify_traffic(vehicle_count):

    if vehicle_count <= 7:
        return "Low"

    elif vehicle_count <= 13:
        return "Medium"

    else:
        return "High"


# Apply classification
df["traffic_level"] = df["total_vehicles"].apply(classify_traffic)


# ---------------------------------------------------------
# Save results
# ---------------------------------------------------------

df.to_csv(output_file, index=False)

print("Traffic classification completed!")
print("Images processed:", len(df))
print("Output saved to:", output_file)

print("\nTraffic distribution:")
print(df["traffic_level"].value_counts())

print("\nSample results:")
print(df.head(10))